server {
    listen 80;
    server_name localhost;

    # Cấu hình để up file dung lượng lớn
    client_max_body_size 100M;

    # 1. Chuyển tiếp API sang Backend container
    location /api/ {
        # 'backend' là tên service trong docker-compose.yml
        # Port 8080 là port nội bộ của container backend
        proxy_pass http://backend:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Phục vụ Frontend tĩnh (từ thư mục dist)
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Rewrite URL phục vụ React Router
        try_files $uri $uri/ /index.html;
    }
}
